# Generated by Django 5.0.6 on 2024-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyinfo',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='facultyinfo',
            old_name='subject',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='facultyinfo',
            name='picture',
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
